---
# handlers file for mapr-hive

- name: reconfigure roles
  become: yes
  become_user: root
  command: /opt/mapr/server/configure.sh -R

- name: restart hiveserver2
  become: yes
  become_user: '{{mapr_admin_username}}'
  command: maprcli node services -name hs2 -action restart -filter csvc==hs2

- name: restart hivemeta
  become: yes
  become_user: '{{mapr_admin_username}}'
  command: maprcli node services -name hivemeta -action restart -filter csvc==hivemeta
